<p style="text-align: center;"><img src="/spiral.gif" width="68" height="68" alt="Spiral Logo"/></p>

<h3>Links</h3>
<ul style="list-style:none;">
 <li><a href="/about/">About</a></li>
 <li><a href="/archive/">Archive</a></li>
 <li><a href="/tags/">Tags</a></li>
</ul>

<h3>Search</h3>
<p>Search prior entries:</p>
 <form method="get" action="/cgi-bin/search/namazu.cgi">
    <input type="text" name="query" />
    <input type="hidden" name="submit" value="Search"/>
    <input type="hidden" name="max" value="30" />
    <input type="hidden" name="sort" value="score" />
  </form>

<h3>RSS Feed</h3>
<ul style="list-style:none;">
 <li><a href="/index.rss"><img src="/xml.gif" alt="Subscribe to feed" width="36" height="14" /></a></li>
</ul>